-- =====================================================================
-- RMU Internship Tracker - v2 Migration 008
-- File: migrations/008_placements.sql
--
-- Splits the student's "letter request" from where they actually
-- ended up working. The current `requests` row was conflating the
-- two. From now on:
--
--   requests   = "I want an attachment letter" (always generic
--                'TO WHOM IT MAY CONCERN' going forward)
--   placements = "I've secured a company — here are the details"
--
-- Logbooks and the final supervisor evaluation will both attach
-- to the placement (subsequent migrations).
--
-- The supervisor_token columns are added now even though the
-- token-based supervisor flow lands in a later sprint, so we don't
-- need a follow-up ALTER for them.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS.
-- =====================================================================

START TRANSACTION;

CREATE TABLE IF NOT EXISTS `placements` (
    `id`                          INT(11)      NOT NULL AUTO_INCREMENT,
    `student_id`                  INT(11)      NOT NULL,
    `request_id`                  INT(11)      DEFAULT NULL,

    -- Company side
    `company_name`                VARCHAR(150) NOT NULL,
    `company_address`             TEXT         NOT NULL,
    `company_department`          VARCHAR(150) DEFAULT NULL,  -- "DEPARTMENT/OFFICE" on the weekly log

    -- On-the-job supervisor
    `supervisor_name`             VARCHAR(150) NOT NULL,
    `supervisor_email`            VARCHAR(150) NOT NULL,
    `supervisor_title`            VARCHAR(100) DEFAULT NULL,
    `supervisor_phone`            VARCHAR(30)  DEFAULT NULL,

    -- Period
    `start_date`                  DATE         NOT NULL,
    `end_date`                    DATE         NOT NULL,
    `status`                      ENUM('active','completed','cancelled') NOT NULL DEFAULT 'active',

    -- Calendar tagging (for reporting)
    `academic_year_id`            INT(11)      DEFAULT NULL,
    `semester_id`                 INT(11)      DEFAULT NULL,

    -- Token used by the on-the-job supervisor for weekly remarks
    -- and the final evaluation (no account needed). Issued when
    -- the placement is registered, expires after 60 days, can be
    -- regenerated by the student or department secretary.
    `supervisor_token`            VARCHAR(64)  DEFAULT NULL,
    `supervisor_token_expires_at` TIMESTAMP    NULL DEFAULT NULL,

    `created_at`                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`                  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
                                              ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_supervisor_token` (`supervisor_token`),
    KEY `idx_p_student` (`student_id`),
    KEY `idx_p_request` (`request_id`),
    KEY `idx_p_year`    (`academic_year_id`),
    KEY `idx_p_sem`     (`semester_id`),

    CONSTRAINT `fk_p_student`  FOREIGN KEY (`student_id`)        REFERENCES `users`           (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_p_request`  FOREIGN KEY (`request_id`)        REFERENCES `requests`        (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_p_year`     FOREIGN KEY (`academic_year_id`)  REFERENCES `academic_years`  (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_p_semester` FOREIGN KEY (`semester_id`)       REFERENCES `semesters`       (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

COMMIT;
